web/web/router.ex
defmodule Overtwitch.Router do
  use Overtwitch.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Overtwitch do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :index
    post "/fetch", HomeController, :fetch
    post "/import", HomeController, :import
    get "/stats", StatsController, :index
    resources "/votes", VotesController
    get "/tagged", VotesController, :tagged
    post "/export", VotesController, :export
  end

  # Other scopes may use custom stacks.
  # scope "/api", Overtwitch do
  #   pipe_through :api
  # end
end

web/web/views/layout_view.ex
defmodule Overtwitch.LayoutView do
  use Overtwitch.Web, :view
end

web/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Overtwitch!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <header>
        <%= link("Home", to: home_path(@conn, :index)) %>
      </header>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>